// <auto-generated />
using System;
using AgentController.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentController.Migrations.Migrations
{
    [DbContext(typeof(AgentControllerDbContext))]
    [Migration("20260716000200_AddRepositoryHostConnectionKeyToRepositories")]
    partial class AddRepositoryHostConnectionKeyToRepositories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.AgentRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousRunId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("RuntimeRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("IX_AgentRuns_EnvironmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AgentRuns_Status");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("IX_AgentRuns_WorkItemId");

                    b.HasIndex("Status", "LastHeartbeatAt")
                        .HasDatabaseName("IX_AgentRuns_Status_LastHeartbeatAt");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.EnvironmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("MetadataJson");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_Environments_RunId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Environments_Status");

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.LifecycleEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "CreatedAt")
                        .HasDatabaseName("IX_LifecycleEvents_RunId_CreatedAt");

                    b.HasIndex("RunId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_LifecycleEvents_RunId_EventId_Unique")
                        .HasFilter("[EventId] IS NOT NULL");

                    b.ToTable("LifecycleEvents", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedPathsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("AllowedPathsJson");

                    b.Property<string>("AzureDevOpsEnvironmentKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryHostConnectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeEnvironmentKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.RepositoryHostConnectionEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccessTokenReferenceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccessTokenReferenceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("RepositoryHostConnections", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.ReworkCycleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedbackBundleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackBundleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewRunId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackBundleId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReworkCycles_FeedbackBundleId");

                    b.HasIndex("WorkItemId", "Status")
                        .HasDatabaseName("IX_ReworkCycles_WorkItemId_Status");

                    b.ToTable("ReworkCycles", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.ReworkFeedbackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackBundleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackBundleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstQualifyingCommentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastQualifyingCommentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginatingRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ReworkFeedback_Status");

                    b.HasIndex("PullRequestId", "FeedbackBundleId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReworkFeedback_PullRequestId_FeedbackBundleId");

                    b.ToTable("ReworkFeedback", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.RuntimeEnvironmentEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardEnvironmentVariablesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadoutsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PiExecutablePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PtyWrapperArgs")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PtyWrapperPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceRoot")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("RuntimeEnvironments", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.SecretEntity", b =>
                {
                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Secrets", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.WorkItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("AcceptanceCriteriaJson");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceMetadataJson");

                    b.Property<string>("Status")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("TagsJson");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoKey")
                        .HasDatabaseName("IX_WorkItems_RepoKey");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_WorkItems_Source");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_WorkItems_Status_LeaseExpiresAt");

                    b.ToTable("WorkItems", (string)null);
                });

            modelBuilder.Entity("AgentController.Infrastructure.Data.Entities.WorkSourceEnvironmentEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveState")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedState")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatEnvironmentVariable")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("WorkSourceEnvironments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
